import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { processBundleV2ResourceSchema } from "../../../packages/contracts/dist/index.js";
import { buildProcessBundleV2, validateProcessBundleV2 } from "../../../packages/process-bundle/dist/index.js";

const root = dirname(fileURLToPath(import.meta.url));
const out = resolve(root, "v2");
const now = "2026-08-16T21:00:00.000Z";
const processVersionId = "53000000-0000-4000-8000-000000000001";
const bindingSetVersionId = "54000000-0000-4000-8000-000000000001";
const releaseId = "55000000-0000-4000-8000-000000000001";
const bpmn = await readFile(resolve(root, "process.bpmn"), "utf8");
const ids = ["Activity_Present", "Activity_Check", "Activity_Deliver"];
const semantic = ["biblioteca.usuario.apresentar.material", "biblioteca.atendente.conferir.condicoes", "biblioteca.atendente.entregar.material"];
const labels = ["Apresentar identificação e material no balcão", "Conferir vínculo e condições de empréstimo", "Entregar material e informar data de devolução"];
const uuid = (n) => `50000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const metadata = (n, key, title, visibility = "PUBLIC") => ({ id: uuid(n), key, version: "1.0.0", visibility, status: "DRAFT", title, createdAt: now, updatedAt: now, labels: {} });
const wrap = (kind, n, key, title, spec, visibility) => ({ apiVersion: "processos.furg.br/v2", kind, metadata: metadata(n, key, title, visibility), spec });
const resources = [
  ["process/process.json", wrap("ProcessDefinition", 1, "processo.biblioteca.emprestimo.presencial", "Empréstimo presencial de material bibliográfico", { definitionId: "52000000-0000-4000-8000-000000000001", processVersionId, bindingSetVersionId, releaseId, profile: "ANALYZABLE", perspective: "AS_IS", ownerUnitRef: "unidade.sib", participantUnitRefs: ["unidade.biblioteca"], taxonomyRefs: ["dominio.biblioteca"], audienceRefs: ["vinculo.discente", "vinculo.servidor"], bpmnPath: "process/process.bpmn", normativeBasisRefs: [] })],
  ["catalogs/context.json", wrap("InstitutionalContextCatalog", 9, "processo.biblioteca.emprestimo.contexto", "Contexto institucional da biblioteca", { organizationUnits: [{ key: "unidade.sib", acronym: "SiB", label: "Sistema de Bibliotecas" }, { key: "unidade.biblioteca", acronym: "BIB", label: "Biblioteca de atendimento", parentRef: "unidade.sib" }], affiliations: [{ key: "vinculo.discente", label: "Discente" }, { key: "vinculo.servidor", label: "Servidor" }], positions: [], domains: [{ key: "dominio.biblioteca", label: "Serviços de biblioteca" }] })],
  ["process/phases.json", wrap("PhaseCatalog", 2, "processo.biblioteca.emprestimo.fases", "Fases do empréstimo", { phases: [{ key: "fase.solicitacao", label: "Solicitação presencial", publicLabel: "Solicitação", expectedDuration: "PT5M", order: 0, elementRefs: [semantic[0]] }, { key: "fase.conferencia", label: "Conferência e entrega", publicLabel: "Conferência e entrega", expectedDuration: "PT10M", order: 1, elementRefs: semantic.slice(1) }] })],
  ["bindings/elements.json", wrap("ElementBindingCatalog", 3, "processo.biblioteca.emprestimo.elementos", "Elementos do empréstimo", { elements: ids.map((id, index) => ({ bpmnElementId: id, semanticId: semantic[index], elementType: "manualTask", label: labels[index], phaseRef: index ? "fase.conferencia" : "fase.solicitacao", visibility: "PUBLIC", publicLabel: labels[index] })) })],
  ["bindings/operational-traceability.json", wrap("OperationalTraceabilityCatalog", 4, "processo.biblioteca.emprestimo.rastreabilidade", "Rastreabilidade do empréstimo", { activities: semantic.map((activityRef, index) => ({ activityRef, executionMode: "HUMAN_EXTERNAL", actorRefs: [index ? "ator.atendente.biblioteca" : "ator.usuario.biblioteca"], organizationUnitRefs: ["unidade.biblioteca"], interactionPointRefs: [], completionActions: [{ key: `acao.${activityRef}`, label: labels[index], type: "COMPLETE", operationRefs: [], formRefs: [], policyRefs: [], preconditions: [], effects: [], evidenceRefs: ["evidencia.procedimento.biblioteca"] }], inputRefs: [], outputRefs: [], timingPolicyRefs: [], evidenceRefs: ["evidencia.procedimento.biblioteca"], externalProcedure: { location: "Balcão de atendimento da biblioteca", procedureRef: "procedimento.emprestimo.presencial" }, mappingStatus: "COMPLETE" })) })],
  ["catalogs/access.json", wrap("AccessCatalog", 5, "processo.biblioteca.emprestimo.acesso", "Acesso ao empréstimo", { actors: [{ key: "ator.usuario.biblioteca", label: "Pessoa com vínculo ativo", kind: "AFFILIATION" }, { key: "ator.atendente.biblioteca", label: "Atendente da biblioteca", kind: "ORGANIZATIONAL_ROLE" }], profiles: [], groups: [], grants: [], policies: [{ key: "politica.vinculo.ativo", label: "Vínculo ativo", layer: "CAPABILITY", effect: "ALLOW", expressionLanguage: "CEL", expression: "vinculo.ativo", description: "O empréstimo depende de vínculo institucional ativo.", evidenceRefs: ["evidencia.procedimento.biblioteca"] }] })],
  ["projections/projections.json", wrap("ProjectionCatalog", 6, "processo.biblioteca.emprestimo.projecoes", "Projeção pública do empréstimo", { projections: [{ key: "projecao.biblioteca.emprestimo.publica", audience: "PUBLIC", title: "Como retirar um material na biblioteca", summary: "Leve o material ao balcão, apresente sua identificação e confira a data de devolução.", phases: [{ key: "publica.solicitacao", label: "Apresente o material", description: "Dirija-se ao balcão com identificação institucional.", internalElementRefs: [semantic[0]], responsibleLabel: "Pessoa solicitante", expectedDurationLabel: "Cerca de 5 minutos", nextPhaseRefs: ["publica.conferencia"] }, { key: "publica.conferencia", label: "Aguarde a conferência", description: "A biblioteca confere as condições e informa a devolução.", internalElementRefs: semantic.slice(1), responsibleLabel: "Atendimento da biblioteca", expectedDurationLabel: "Cerca de 10 minutos", nextPhaseRefs: [] }], excludedResourceRefs: [] }] })],
  ["provenance/provenance.json", wrap("ProvenanceCatalog", 7, "processo.biblioteca.emprestimo.proveniencia", "Proveniência do exemplo", { sourceArtifacts: [{ key: "fonte.procedimento.biblioteca", kind: "PROCEDURE", label: "Procedimento de exemplo para teste do contrato", location: { path: "artifacts/examples/emprestimo-biblioteca" }, capturedAt: now }], evidence: [{ key: "evidencia.procedimento.biblioteca", label: "Procedimento documental do empréstimo", status: "DOCUMENTED", confidence: 0.8, sourceArtifactRefs: ["fonte.procedimento.biblioteca"], validatesRefs: semantic }] })],
  ["releases/release.json", wrap("ProcessRelease", 8, "processo.biblioteca.emprestimo.release.1", "Release do exemplo de biblioteca", { releaseId, processDefinitionRef: "processo.biblioteca.emprestimo.presencial", processVersionId, bindingSetVersionId, sourceArtifactRefs: ["fonte.procedimento.biblioteca"] })],
];
for (const [, value] of resources) processBundleV2ResourceSchema.parse(value);
const files = [{ path: "process/process.bpmn", content: bpmn, mediaType: "application/xml", visibility: "PUBLIC" }, ...resources.map(([path, value]) => ({ path, content: `${JSON.stringify(value, null, 2)}\n`, mediaType: "application/json", visibility: value.metadata.visibility }))];
const bundle = await buildProcessBundleV2({ profile: "ANALYZABLE", processDefinitionKey: "processo.biblioteca.emprestimo.presencial", processVersionId, bindingSetVersionId, releaseId, createdAt: now, createdBy: "fixture oficial", files });
const report = await validateProcessBundleV2(bundle);
if (!report.valid) throw new Error(JSON.stringify(report.issues, null, 2));
await rm(out, { recursive: true, force: true });
for (const file of files) { const target = resolve(out, file.path); await mkdir(dirname(target), { recursive: true }); await writeFile(target, file.content); }
await writeFile(resolve(out, "validation-report.json"), `${JSON.stringify(report, null, 2)}\n`);
await writeFile(resolve(root, "emprestimo-biblioteca.process-bundle-v2.zip"), bundle);
console.log(JSON.stringify({ valid: report.valid, coverage: report.coverage, issues: report.issues }, null, 2));
