import { useEffect, useState, type FormEvent } from "react";
import { FurgActionRow, FurgButton, FurgDialog, FurgMessage } from "@furg/design-system/react";
import {
  createInformationSchema, createSoftwareOperation, deleteSoftwareOperation, importOpenApi,
  listSoftwareFunctionalities, updateSoftwareOperation,
  type CatalogSoftwareOperation, type SoftwareFunctionality, type SoftwareOperationInput,
} from "./api";

function slugify(value: string) {
  return value.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
}

export function InformationSchemaDialog({ current, isOpen, onClose, onSaved }: { current?: any; isOpen: boolean; onClose: () => void; onSaved: () => Promise<void> | void }) {
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [kind, setKind] = useState("INFORMATION_ASSET");
  const [visibility, setVisibility] = useState<"PUBLIC" | "INTERNAL" | "RESTRICTED">("INTERNAL"); const [document, setDocument] = useState("{}");
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { if (!isOpen) return; setName(current?.asset?.name ?? ""); setDescription(current?.asset?.description ?? ""); setKind(current?.asset?.kind ?? "INFORMATION_ASSET"); setVisibility(current?.visibility ?? "INTERNAL"); setDocument(JSON.stringify(current?.jsonSchema ?? { $schema: "https://json-schema.org/draft/2020-12/schema", type: "object", properties: {} }, null, 2)); setError(undefined); }, [current, isOpen]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { const jsonSchema = JSON.parse(document) as Record<string, unknown>; await createInformationSchema({ assetId: current?.assetId, name, slug: slugify(name), description, kind, visibility, jsonSchema }); await onSaved(); onClose(); } catch (cause) { setError(cause instanceof SyntaxError ? "O conteúdo informado não é um JSON válido." : cause instanceof Error ? cause.message : "Não foi possível salvar o contrato de dados."); } finally { setSaving(false); } }
  return <FurgDialog description={current ? "Uma nova versão preservará a versão atual e seus vínculos históricos." : "Cadastre um ativo e sua primeira versão validável em JSON Schema 2020-12."} isOpen={isOpen} onClose={onClose} title={current ? "Criar nova versão do contrato" : "Criar contrato de dados"}><form className="catalog-editor-form" onSubmit={submit}>{error ? <FurgMessage title="Contrato não salvo" message={error} tone="danger" /> : null}<div className="catalog-editor-grid"><label><span>Nome do ativo</span><input minLength={3} onChange={(event) => setName(event.target.value)} required value={name} /></label><label><span>Tipo</span><select onChange={(event) => setKind(event.target.value)} value={kind}><option value="INFORMATION_ASSET">Ativo de informação</option><option value="DOCUMENT">Documento</option><option value="FILE">Arquivo</option><option value="REFERENCE_CATALOG">Catálogo de referência</option><option value="BUSINESS_CONCEPT">Conceito de negócio</option></select></label><label className="catalog-editor-wide"><span>Descrição</span><input minLength={10} onChange={(event) => setDescription(event.target.value)} required value={description} /></label><label><span>Visibilidade</span><select onChange={(event) => setVisibility(event.target.value as typeof visibility)} value={visibility}><option value="INTERNAL">Institucional</option><option value="PUBLIC">Pública</option><option value="RESTRICTED">Restrita</option></select></label><label className="catalog-editor-wide"><span>JSON Schema 2020-12</span><textarea className="catalog-code-editor" onChange={(event) => setDocument(event.target.value)} required rows={18} spellCheck={false} value={document} /></label></div><FurgActionRow align="end"><FurgButton disabled={saving} onClick={onClose} type="button" variant="text">Cancelar</FurgButton><FurgButton loading={saving} type="submit">Validar e salvar versão</FurgButton></FurgActionRow></form></FurgDialog>;
}

function useFunctionalities(isOpen: boolean) {
  const [items, setItems] = useState<SoftwareFunctionality[]>([]); const [error, setError] = useState<string>();
  useEffect(() => { if (!isOpen) return; void listSoftwareFunctionalities().then(setItems).catch((cause) => setError(cause instanceof Error ? cause.message : "Não foi possível carregar as funcionalidades.")); }, [isOpen]);
  return { items, error };
}

export function OpenApiImportDialog({ isOpen, onClose, onSaved }: { isOpen: boolean; onClose: () => void; onSaved: (message: string) => Promise<void> | void }) {
  const { items, error: loadingError } = useFunctionalities(isOpen); const [functionalityId, setFunctionalityId] = useState(""); const [document, setDocument] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { if (isOpen) { setFunctionalityId(""); setDocument(""); setError(undefined); } }, [isOpen]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { const result = await importOpenApi(functionalityId, document); await onSaved(`${result.imported} operações da versão ${result.version} foram importadas ou atualizadas.`); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível importar o documento OpenAPI."); } finally { setSaving(false); } }
  return <FurgDialog description="Selecione a funcionalidade de destino. Operações com o mesmo identificador e versão serão atualizadas sem duplicação." isOpen={isOpen} onClose={onClose} title="Importar documento OpenAPI"><form className="catalog-editor-form" onSubmit={submit}>{error || loadingError ? <FurgMessage title="Importação indisponível" message={error ?? loadingError ?? ""} tone="danger" /> : null}<label><span>Funcionalidade de destino</span><select onChange={(event) => setFunctionalityId(event.target.value)} required value={functionalityId}><option value="">Selecione uma funcionalidade</option>{items.map((item) => <option key={item.id} value={item.id}>{item.module.system.name} › {item.module.name} › {item.name}</option>)}</select></label><label><span>Documento OpenAPI em YAML ou JSON</span><textarea className="catalog-code-editor" onChange={(event) => setDocument(event.target.value)} placeholder={'openapi: 3.1.0\ninfo:\n  title: Minha API\n  version: 1.0.0\npaths: {}'} required rows={18} spellCheck={false} value={document} /></label><FurgActionRow align="end"><FurgButton disabled={saving} onClick={onClose} type="button" variant="text">Cancelar</FurgButton><FurgButton disabled={!functionalityId || !document.trim()} loading={saving} type="submit">Validar e importar</FurgButton></FurgActionRow></form></FurgDialog>;
}

export function SoftwareOperationDialog({ current, isOpen, onClose, onSaved }: { current?: CatalogSoftwareOperation; isOpen: boolean; onClose: () => void; onSaved: (message: string) => Promise<void> | void }) {
  const { items, error: loadingError } = useFunctionalities(isOpen); const [form, setForm] = useState<SoftwareOperationInput>({ functionalityId: "", operationId: "", method: "", path: "", version: "1.0.0", deprecated: false }); const [saving, setSaving] = useState(false); const [error, setError] = useState<string>();
  useEffect(() => { if (!isOpen) return; setForm({ functionalityId: current?.functionalityId ?? "", operationId: current?.operationId ?? "", method: current?.method ?? "", path: current?.path ?? "", version: current?.version ?? "1.0.0", deprecated: current?.deprecated ?? false }); setError(undefined); }, [current, isOpen]);
  function update<K extends keyof SoftwareOperationInput>(key: K, value: SoftwareOperationInput[K]) { setForm((previous) => ({ ...previous, [key]: value })); }
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(undefined); try { if (current) await updateSoftwareOperation(current.id, form); else await createSoftwareOperation(form); await onSaved(current ? "Operação atualizada no catálogo." : "Operação adicionada ao catálogo."); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível salvar a operação."); } finally { setSaving(false); } }
  async function remove() { if (!current || !window.confirm("Remover esta operação do catálogo?")) return; setSaving(true); setError(undefined); try { await deleteSoftwareOperation(current.id); await onSaved("Operação removida do catálogo."); onClose(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Não foi possível remover a operação."); } finally { setSaving(false); } }
  return <FurgDialog description="O cadastro manual permite corrigir um pequeno desvio sem repetir uma importação completa." isOpen={isOpen} onClose={onClose} title={current ? "Editar operação" : "Adicionar operação manualmente"}><form className="catalog-editor-form" onSubmit={submit}>{error || loadingError ? <FurgMessage title="Operação não salva" message={error ?? loadingError ?? ""} tone="danger" /> : null}<div className="catalog-editor-grid"><label className="catalog-editor-wide"><span>Funcionalidade</span><select onChange={(event) => update("functionalityId", event.target.value)} required value={form.functionalityId}><option value="">Selecione uma funcionalidade</option>{items.map((item) => <option key={item.id} value={item.id}>{item.module.system.name} › {item.module.name} › {item.name}</option>)}</select></label><label><span>Identificador da operação</span><input onChange={(event) => update("operationId", event.target.value)} required value={form.operationId} /></label><label><span>Versão</span><input onChange={(event) => update("version", event.target.value)} required value={form.version} /></label><label><span>Método</span><input onChange={(event) => update("method", event.target.value)} placeholder="Ex.: POST" value={form.method} /></label><label><span>Caminho</span><input onChange={(event) => update("path", event.target.value)} placeholder="Ex.: /pedidos/{id}/enviar" value={form.path} /></label><label className="catalog-checkbox catalog-editor-wide"><input checked={Boolean(form.deprecated)} onChange={(event) => update("deprecated", event.target.checked)} type="checkbox" /><span>Operação descontinuada</span></label></div><FurgActionRow align="end">{current ? <FurgButton disabled={saving} onClick={() => void remove()} type="button" variant="text">Remover operação</FurgButton> : null}<FurgButton disabled={saving} onClick={onClose} type="button" variant="text">Cancelar</FurgButton><FurgButton loading={saving} type="submit">Salvar operação</FurgButton></FurgActionRow></form></FurgDialog>;
}
